import type { CaseData, Difficulty } from '../types/index.js';
import { generateId, now } from '../utils/index.js';

const TEMPLATE: Omit<CaseData, 'id' | 'createdAt' | 'difficulty'> = {
  title: '深夜仓库的最后一幕',

  // ─── M0: 行动指挥 Briefing ─────────────────────────────────────────────────
  missionBriefing: {
    directorName: 'NOAH',
    directorTitle: '首席调查AI · NOAH',
    openingLine: '48小时之内，有人以为自己做到了完美犯罪。',
    script:
      '案件编号 CASE-2026-0715，保密等级 TOP SECRET。\n' +
      '过去48小时内，本市东区工业路废弃仓库发生一起高度可疑命案。\n' +
      '死者林雪峰，45岁，企业家。法医初步确认死亡时间为7月13日22:00至23:30之间。\n' +
      '现场遗留多处矛盾证据，警方已排除随机作案可能，指向预谋或激情犯罪。\n' +
      '三名关联人员已处于软性控制状态，等待审讯。\n' +
      '你将作为AI特别调查员接管本案，拥有Level 2调查权限。\n' +
      '预计调查时间：30分钟。请前往证据分析室，立即开始。',
    revealedFacts: [
      { atSecond: 2,  label: '案件编号', value: 'CASE-2026-0715' },
      { atSecond: 5,  label: '保密等级', value: 'TOP SECRET' },
      { atSecond: 9,  label: '案件等级', value: '★★★☆☆' },
      { atSecond: 13, label: '死亡时间', value: '22:00 - 23:30（7月13日）' },
      { atSecond: 17, label: '当前状态', value: 'OPEN · 待侦破' },
      { atSecond: 22, label: '负责特工', value: '你' },
    ],
    missionOrder: '前往证据分析室，立即开始。',
    urgencyLevel: 'high',
    durationSeconds: 28,
  },

  // ─── M1: 情报局 ────────────────────────────────────────────────────────────
  intelligence: {
    caseLevel: '★★★☆☆',
    securityLevel: 'TOP SECRET',
    riskLevel: 'B',
    investigationPermission: 'Level 2',
    caseNumber: 'CASE-2026-0715',
    responsibleAI: 'NOAH',
    estimatedTime: 30,
    briefing: '侦探，你有30分钟破获此案。目标已于深夜死亡，三名嫌疑人各藏秘密——其中一人说谎。',
  },

  // ─── M2: 案件卷宗 ──────────────────────────────────────────────────────────
  dossier: {
    caseNumber: 'CASE-2026-0715',
    coverTitle: '林雪峰命案卷宗 / HOMICIDE CASE FILE',
    dangerLevel: 'HIGH',
    caseStatus: 'OPEN',
    department: '联邦特别调查局·暗罪科',
    filingDate: '2026-07-14 06:30',
    summary: '2026年7月13日夜，商人林雪峰被发现死于本市废弃仓库内。死者头部遭受钝器重击，现场发现血迹及打斗痕迹。初步调查显示，死者与三名已知关联人存在重大利益冲突。本局已对上述人员实施软性控制，等待进一步审讯。',
    confidentialityClause: '本卷宗属绝密级别，未经授权不得复制或传阅。违者将依法承担法律责任。',
    investigationObjectives: [
      '确认死者真实死亡时间及死亡原因',
      '锁定案发时间嫌疑人行踪',
      '找出与案件相关的关键物证并建立证据链',
      '排除无关人员，确定唯一真凶',
    ],
    caseBackground: '林雪峰，45岁，本地知名房地产企业家，近年因资金链紧张涉及多起商业纠纷。与其合伙人王建国因撤资问题矛盾激化，前妻陈美玲因财产分割问题对其提起诉讼，秘书李晓雯则因个人情感问题与死者存在复杂纠葛。三人均有作案动机，且均无可靠的不在场证明。',
  },

  // ─── M3: 法医报告 ──────────────────────────────────────────────────────────
  forensicReport: {
    reportId: 'FR-CASE-2026-0715-001',
    examinedBy: 'Dr. 方晴',
    examinationDate: '2026-07-14',
    deathTime: '22:00 - 23:30（7月13日）',
    bodyTemperature: '31.2°C（低于正常体温5.8°C，推算死亡约4-5小时）',
    lividityMarks: '尸斑呈暗紫色，分布于背部及后颈，已固定，说明死后未被翻动',
    rigorMortis: '全身尸僵完全，下颌及四肢均无法活动，符合死亡4-6小时判断',
    bloodAnalysis: 'B型血，凝血正常，血液中检出微量镇静剂成分（苯二氮䓬类），浓度不足以致死',
    dna: '死者头发及指甲缝中检出第三方DNA样本，待比对',
    wounds: [
      {
        location: '枕部左侧',
        type: '钝器伤',
        description: '长约8cm的线性裂伤，伴颅骨骨折，硬膜外血肿，系主要致死伤',
        weaponType: '圆形截面钝器，直径约4cm，推测为金属管或木棍',
      },
      {
        location: '右前臂',
        type: '防御性擦伤',
        description: '多处浅表擦伤，方向不规则，系挡格时形成',
        weaponType: '同一凶器或地面摩擦',
      },
    ],
    toxicology: '苯二氮䓬类药物阳性（低浓度），乙醇阴性，其他毒物阴性',
    pathology: '颅内出血为主要死因，大脑枕叶受压，脑干功能衰竭',
    stomachContents: '半消化状米饭及肉类，推测死前2-3小时进食，与案发当晚19:30晚餐时间吻合',
    causeOfDeath: '枕部钝器伤致颅内出血，脑干衰竭死亡',
    forensicConclusion: '死者于7月13日22:00至23:30之间遭钝器击打头部致死。现场痕迹显示存在搏斗，但力量对比悬殊，死者未能有效反抗。凶器尚未找到，建议在仓库半径50米内重点搜索。',
    additionalNotes: '指甲缝DNA样本正在鉴定中，结果可能改变嫌疑人排序。',
  },

  // ─── M4: 案发现场 ──────────────────────────────────────────────────────────
  crimeScene: {
    setting: '废弃工业仓库',
    address: '本市东区工业路47号，已废弃仓库C栋',
    discoveryTime: '2026-07-14 02:15',
    reportedBy: '夜间巡逻保安 老陈',
    weatherCondition: '阴天，间歇小雨，能见度约30米，地面湿滑',
    description: '昏黄的路灯将仓库投影拉得极长。生锈的铁门半开着，铰链上有新鲜的划痕——有人强行进入。内部空气凝重，弥漫着机油与血腥的混合气息。中央区域一具身着深色西装的男性仰面倒地，右手微微张开，仿佛最后一刻还想抓住什么。地面血迹从躯体向右延伸约1.5米，周围散落破碎的木板和翻倒的铁桶。',
    keyAreas: [
      {
        name: '中央区域（尸体发现处）',
        description: '仓库中心，地面有大量血迹，周围物品被翻动',
        cluesFound: ['血迹痕迹', '散落的西装纽扣', '受害者手机（屏幕破裂）'],
      },
      {
        name: '东侧储物区',
        description: '金属货架区，有一个货架被推倒',
        cluesFound: ['指纹（待鉴定）', '一枚金属戒指'],
      },
      {
        name: '北侧入口',
        description: '废弃仓库的主要出入口，铁门被撬开',
        cluesFound: ['门锁破坏痕迹', '泥脚印（至少两种鞋码）'],
      },
    ],
    physicalEvidence: ['破碎手机', '散落纽扣', '金属戒指', '血迹', '泥脚印'],
    bloodSplatterPattern: '以尸体为中心的接触型血迹，无飞溅型，说明击打次数少但力度极大',
    entryExitPoints: ['北侧主入口（被撬开）', '东侧小窗（有攀爬痕迹，但灰尘未扰动，可能为迷惑）'],
  },

  // ─── M5: 受害者 ────────────────────────────────────────────────────────────
  victim: {
    name: '林雪峰',
    gender: 'male',
    age: 45,
    occupation: '房地产企业家',
    background: '白手起家的商人，从建材生意起步，20年间将公司扩张至本地Top5房企。近年因激进扩张导致资金链紧张，开始秘密转移资产。外表光鲜，私下手段强硬，与多名商业伙伴存在纠纷。',
    lastKnownLocation: '案发仓库',
    lastSeenTime: '2026-07-13 21:40（仓库附近监控）',
    relationships: [
      { name: '陈美玲', relation: '前妻', notes: '离婚诉讼中，财产分割金额巨大' },
      { name: '王建国', relation: '商业伙伴', notes: '撤资纠纷激化，王声称损失数百万' },
      { name: '李晓雯', relation: '私人秘书', notes: '个人情感纠葛，承诺未兑现' },
    ],
    secrets: [
      '秘密在海外设有壳公司，正在转移国内资产',
      '已与新投资人谈妥，准备彻底抛弃王建国',
    ],
    digitalFootprint: '手机通话记录显示案发前2小时曾拨打一个未登记号码3次，短信记录已被删除，但残留缓存显示内容为"到了没""在哪"等催促性语句',
  },

  // ─── M6+M7: 嫌疑人 + 审讯 ─────────────────────────────────────────────────
  suspects: [
    {
      id: 's1',
      name: '陈美玲',
      gender: 'female',
      age: 38,
      occupation: '律师',
      relationship: '前妻',
      alibi: '案发时在律所加班，助理可证明（但助理21:30离开，之后无法核实）',
      motive: '财产分割不公，证据显示林雪峰私自转移资产',
      personality: '冷静理性，极具城府',
      secrets: ['曾雇私家侦探调查林雪峰资产转移', '发现了林雪峰海外账户但未公开'],
      isGuilty: false,
      psychProfile: {
        mentalState: '表面极度冷静，刻意控制情绪，语言精准',
        stressLevel: 38,
        lyingProbability: 25,
        confidenceLevel: 82,
        heartbeatBPM: 88,
        responseStyle: '防御性，每个问题先反问一个问题再回答',
        speakingSpeed: '缓慢',
        isEvasive: true,
        microExpressions: ['谈及资产时右眼轻微抽动', '提到林雪峰时嘴角细微下压'],
        interrogationNotes: '她知道的比说出来的多得多。作为律师，她非常清楚哪些话不能说。',
      },
      interrogationScript: [
        {
          question: '案发当晚你在哪里？',
          answer: '律所。我一直在准备下周的庭审材料。',
          isLie: false,
          clueHidden: '她没提到助理21:30已离开，她的独处时间存在空白',
        },
        {
          question: '你雇人调查过林雪峰吗？',
          answer: '这是我的合法权利。离婚案件需要财产评估，我委托了专业机构。',
          isLie: false,
          clueHidden: '她把私家侦探说成了"专业机构"，但实际调查内容远超财产评估',
        },
      ],
    },
    {
      id: 's2',
      name: '王建国',
      gender: 'male',
      age: 50,
      occupation: '商业伙伴',
      relationship: '合作伙伴',
      alibi: '案发时在家，妻子可证明（但妻子当晚吃了安眠药早睡）',
      motive: '林雪峰准备单方面撤资，导致王建国深陷高利贷',
      personality: '城府极深，外表温和，内心决绝',
      secrets: ['公司账目造假', '已向黑道借贷300万，催债电话不断', '案发前一周曾多次联系林雪峰要求谈判均遭拒绝'],
      isGuilty: true,
      psychProfile: {
        mentalState: '高度焦虑但强行压制，偶发肢体小动作暴露紧张',
        stressLevel: 78,
        lyingProbability: 85,
        confidenceLevel: 35,
        heartbeatBPM: 118,
        responseStyle: '绕弯，反复强调自己的损失和受害者角色',
        speakingSpeed: '急促，有时中途停顿重新组织语言',
        isEvasive: true,
        microExpressions: ['被问及案发时间时双手交叉护胸', '眼神向左下方偏移（回忆构造）', '提到凶器时微微吞咽'],
        interrogationNotes: '多次矛盾。他声称当晚在家，但手机信号在22:15出现在仓库附近基站。这是关键矛盾点。',
      },
      interrogationScript: [
        {
          question: '案发当晚22:00你在哪里？',
          answer: '在家，一直在家……我妻子可以作证。',
          isLie: true,
          clueHidden: '手机基站数据显示22:15他的手机出现在仓库附近1.2公里处',
        },
        {
          question: '你和林雪峰最后一次见面是什么时候？',
          answer: '上周三，在他公司。我们谈了一个小时，没谈拢。',
          isLie: true,
          clueHidden: '仓库监控显示当晚21:55有人进入，身形与王建国高度吻合',
        },
      ],
    },
    {
      id: 's3',
      name: '李晓雯',
      gender: 'female',
      age: 28,
      occupation: '私人秘书',
      relationship: '秘书兼前女友',
      alibi: '案发时在家附近便利店购物，有购物记录（21:50），之后独自回家',
      motive: '林雪峰承诺娶她却突然提出解除关系，情感操控导致巨大心理创伤',
      personality: '外表温顺，内有执念，情绪化',
      secrets: ['已怀孕3个月，林雪峰要求她堕胎', '保留了林雪峰大量私密邮件，可作证其违法行为'],
      isGuilty: false,
      psychProfile: {
        mentalState: '真实的悲痛与愤怒，情绪较难控制',
        stressLevel: 65,
        lyingProbability: 20,
        confidenceLevel: 45,
        heartbeatBPM: 102,
        responseStyle: '情绪化，容易因某些词语触发激烈反应',
        speakingSpeed: '不稳定，平静时正常，激动时急促',
        isEvasive: false,
        microExpressions: ['提到林雪峰时眼眶明显泛红', '谈及"婚姻"时拳头微微握紧'],
        interrogationNotes: '她的痛苦是真实的，但要注意：真实的愤怒有时也是作案动机的直接证据。',
      },
      interrogationScript: [
        {
          question: '林雪峰最近有没有联系你？',
          answer: '有。他……他让我"处理掉"。他说这段关系到此为止。（停顿，眼神空洞）',
          isLie: false,
          clueHidden: '"处理掉"指的是孩子，这揭示了她更深的仇恨动机，但也说明她当时处于情绪崩溃边缘，不像冷静策划杀人',
        },
      ],
    },
  ],

  // ─── M8: 证据 ──────────────────────────────────────────────────────────────
  evidence: [
    {
      id: 'e1',
      name: '破碎手机（死者）',
      description: '死者林雪峰的手机，屏幕破裂。通话记录最后一条显示22:03拨出，接通时长0秒（未接听或立即挂断）。',
      location: '死者右手旁，仓库中央区域',
      discoveredAt: '2026-07-14 03:00',
      dna: '表面有死者指纹，未发现第三方生物痕迹',
      fingerprints: '死者指纹，无他人',
      relatedSuspects: ['s1', 's2', 's3'],
      credibility: 90,
      analysisResult: '22:03的未接来电对象是未知号码，与死者手机中删除短信的接收方相同。恢复的缓存显示接收方在催促"到了没"——说明双方有预谋见面。',
      canFormEvidenceChain: true,
      evidenceChainNote: '与手机基站数据（e4）结合，可以确定死者是被约到仓库的，而非随机遇害',
      significance: '证明死者是被约至仓库的，属预谋犯罪',
      category: 'digital',
    },
    {
      id: 'e2',
      name: '金属戒指',
      description: '东侧储物区发现，内侧刻有"W.J.G 2008"字样。戒指为定制款，材质为18K金，表面有新鲜划痕。',
      location: '东侧储物区地面，货架旁',
      discoveredAt: '2026-07-14 03:30',
      dna: '内壁皮肤组织DNA，待鉴定',
      fingerprints: '外表面有指纹，待比对',
      relatedSuspects: ['s2'],
      credibility: 92,
      analysisResult: '"W.J.G 2008"——王建国（Wang Jian Guo），2008年为其创业年份。戒指内侧皮肤DNA与王建国的样本高度匹配（概率97.3%）。',
      canFormEvidenceChain: true,
      evidenceChainNote: '与手机基站数据（e4）形成双重物证：物理DNA + 位置数据，直接锁定真凶',
      significance: '直接物证，将王建国置于案发现场',
      category: 'physical',
    },
    {
      id: 'e3',
      name: '撤资协议（已签字）',
      description: '死者公文包内发现，盖有公司公章的撤资文件，林雪峰已签字，但王建国签字栏空白。',
      location: '死者随身公文包内',
      discoveredAt: '2026-07-14 04:00',
      dna: undefined,
      fingerprints: '林雪峰指纹，以及一枚不明指纹（可能为王建国，待比对）',
      relatedSuspects: ['s2'],
      credibility: 78,
      analysisResult: '文件显示林雪峰已单方面完成签字，准备强制执行撤资。对王建国而言，这意味着项目崩盘和高利贷无法偿还。',
      canFormEvidenceChain: true,
      evidenceChainNote: '建立了动机链：撤资文件（动机）→ 约至仓库（手机）→ 戒指（现场）→ 死亡',
      significance: '揭示真凶的直接杀人动机',
      category: 'documentary',
    },
    {
      id: 'e4',
      name: '手机基站数据',
      description: '电信运营商提供的手机信号位置记录，显示多部手机在案发时段的位置。',
      location: '电信运营商数据库（通过法院调取）',
      discoveredAt: '2026-07-14 08:00',
      dna: undefined,
      fingerprints: undefined,
      relatedSuspects: ['s2'],
      credibility: 95,
      analysisResult: '王建国手机在22:15出现在距离仓库1.2公里的基站，与其"在家"的陈述直接矛盾。该基站覆盖范围不包含其居住地，他必须解释为何出现在此位置。',
      canFormEvidenceChain: true,
      evidenceChainNote: '配合戒指DNA（e2），形成物理位置+生物物证的完整证据链',
      significance: '打穿王建国不在场证明的核心证据',
      category: 'digital',
    },
    {
      id: 'e5',
      name: '便利店监控截图',
      description: '李晓雯所提供的便利店监控，显示其21:50出现在便利店。',
      location: '案发地附近便利店监控系统',
      discoveredAt: '2026-07-14 10:00',
      dna: undefined,
      fingerprints: undefined,
      relatedSuspects: ['s3'],
      credibility: 85,
      analysisResult: '李晓雯在21:50确实在便利店。但便利店距仓库步行仅需18分钟，理论上22:30之前仍有时间到达。然而，其无独立凶器，且心理评估显示她的愤怒更倾向于情绪爆发而非冷静预谋。',
      canFormEvidenceChain: false,
      evidenceChainNote: '更多是为李晓雯减轻嫌疑，而非指向真凶',
      significance: '为李晓雯提供部分时间段的证明，但不能完全排除',
      category: 'digital',
    },
  ],

  // ─── Legacy Timeline ────────────────────────────────────────────────────────
  timeline: [
    { time: '19:30', event: '三人共进晚餐（各自参加，非同桌）', location: '本市不同餐厅', significance: 'low' },
    { time: '21:30', event: '陈美玲助理离开律所，陈美玲独处', location: '律所', significance: 'medium' },
    { time: '21:40', event: '监控最后拍到林雪峰进入仓库附近区域', location: '仓库附近路口', significance: 'critical' },
    { time: '21:50', event: '李晓雯在便利店购物', location: '便利店', significance: 'medium' },
    { time: '22:03', event: '林雪峰拨出最后一通电话（未接通）', location: '仓库内', significance: 'critical' },
    { time: '22:15', event: '王建国手机信号出现在仓库附近基站', location: '工业路基站', significance: 'critical' },
    { time: '22:00~23:30', event: '法医推断死亡时间窗口', location: '仓库内', significance: 'critical' },
    { time: '02:15', event: '保安发现尸体并报警', location: '仓库', significance: 'critical' },
  ],

  // ─── M9: AI推理链 ──────────────────────────────────────────────────────────
  reasoningChain: {
    nodes: [
      {
        id: 'n1',
        step: 1,
        content: '死者手机残存缓存显示有人约他前往仓库，且案发当晚21:40前已到达。',
        type: 'clue',
        relatedEvidence: ['e1'],
        relatedSuspects: ['s1', 's2', 's3'],
        confidence: 95,
      },
      {
        id: 'n2',
        step: 2,
        content: '王建国提供的不在场证明（在家，妻子作证）存在漏洞：妻子服用安眠药早睡，无法核实22:00后的时间。',
        type: 'contradiction',
        relatedEvidence: [],
        relatedSuspects: ['s2'],
        confidence: 80,
      },
      {
        id: 'n3',
        step: 3,
        content: '手机基站数据显示王建国22:15出现在仓库附近，直接推翻其"在家"的陈述。',
        type: 'deduction',
        relatedEvidence: ['e4'],
        relatedSuspects: ['s2'],
        confidence: 95,
      },
      {
        id: 'n4',
        step: 4,
        content: '仓库东侧发现的金属戒指，内刻"W.J.G 2008"，内壁DNA与王建国高度匹配（97.3%）。',
        type: 'clue',
        relatedEvidence: ['e2'],
        relatedSuspects: ['s2'],
        confidence: 97,
      },
      {
        id: 'n5',
        step: 5,
        content: '动机明确：撤资协议已签字，王建国将因此背负高利贷崩盘，走投无路下决意约林雪峰"最后谈判"并失控行凶。',
        type: 'conclusion',
        relatedEvidence: ['e3'],
        relatedSuspects: ['s2'],
        confidence: 92,
      },
    ],
    logicRelations: [
      { fromNodeId: 'n1', toNodeId: 'n2', relation: 'A支持B', description: '死者被约至仓库 + 王建国不在场证明漏洞 = 王建国是约人者的可能性上升' },
      { fromNodeId: 'n2', toNodeId: 'n3', relation: 'A导致B', description: '不在场证明漏洞被基站数据彻底击破' },
      { fromNodeId: 'n3', toNodeId: 'n4', relation: 'A支持B', description: '位置数据 + 物理DNA双重物证，共同指向王建国在场' },
      { fromNodeId: 'n4', toNodeId: 'n5', relation: 'A导致B', description: '王建国在场 + 直接动机 = 确定真凶' },
    ],
    keyBreakthrough: '手机基站数据与戒指DNA的双重突破——王建国谎言被彻底瓦解',
    finalConclusion: '王建国因撤资危机走投无路，约林雪峰至仓库试图最后谈判，争执激化后用仓库内的金属管击打林雪峰头部致死。戒指在搏斗中脱落遗留于现场，成为定罪关键。',
  },

  // ─── M10: 案件重建（电影分镜）──────────────────────────────────────────────
  reconstruction: [
    {
      sceneNumber: 1,
      time: '21:35',
      location: '王建国家中书房',
      characters: ['王建国'],
      action: '王建国盯着桌上的催债电话记录和撤资协议，手握手机，颤抖着拨出一个号码。',
      cameraAngle: '特写',
      narration: '绝望会让一个人做出任何决定。',
      environment: '狭小的书房，散落的账单，墙上挂着昔日的合作照片',
      lighting: '台灯的黄光，阴影浓重',
      emotion: '绝望、孤注一掷',
      soundscape: '远处街道的车声，和沉默中那一声拨号音',
    },
    {
      sceneNumber: 2,
      time: '21:40',
      location: '废弃仓库外',
      characters: ['林雪峰'],
      action: '林雪峰推开半掩的铁门走进仓库，手机屏幕的冷光照亮了他疑惑的表情。',
      cameraAngle: '跟拍',
      narration: '他以为这不过是又一次谈判。他不知道这是最后一次。',
      environment: '夜雨打湿的地面，远处昏黄的路灯，仓库深处的黑暗',
      lighting: '外冷内暗，门口一束逆光',
      emotion: '戒备、轻蔑、一丝不安',
      soundscape: '雨声、铁门锈迹摩擦声、皮鞋踩在碎石上的声音',
    },
    {
      sceneNumber: 3,
      time: '22:00',
      location: '仓库中央区域',
      characters: ['林雪峰', '王建国'],
      action: '两人面对面站立，王建国声音颤抖地请求再给一次机会，林雪峰冷漠地转身。',
      cameraAngle: '过肩镜头',
      narration: '林雪峰已经打定主意。王建国感受到了那份决绝。',
      environment: '昏暗的仓库，周围是废弃的货架和铁桶',
      lighting: '仓库顶部单盏灯，将两人影子拉向不同方向',
      emotion: '绝望爆发前的最后平静',
      soundscape: '雨声渗入屋顶，远处一声低沉的雷',
    },
    {
      sceneNumber: 4,
      time: '22:15',
      location: '仓库中央区域',
      characters: ['林雪峰', '王建国'],
      action: '王建国捡起一根金属管，猛地挥向转身的林雪峰后脑勺。林雪峰没有发出任何声音便倒下。',
      cameraAngle: '俯拍',
      narration: '那一刻，所有的计划、梦想与犯罪，在同一秒钟完成。',
      environment: '血在地面扩散，金属管在落地时发出回响',
      lighting: '顶灯在此刻摇晃了一下',
      emotion: '窒息、震惊、万劫不复',
      soundscape: '金属撞击声，然后是沉重的倒地声，然后是寂静',
    },
    {
      sceneNumber: 5,
      time: '22:35',
      location: '仓库北侧出口',
      characters: ['王建国'],
      action: '王建国慌乱地走向出口，直到此刻才发现手上的戒指不见了。他停顿了五秒，最终没有回头。',
      cameraAngle: '远景',
      narration: '他不知道那枚戒指刻着他的名字，也刻着他命运的转折点。',
      environment: '铁门的阴影，雨已停，地面反光',
      lighting: '路灯背光，人物成剪影',
      emotion: '恐惧、逃脱的本能、那五秒内的犹豫',
      soundscape: '脚步声加快，铁门开合声，然后夜的静默',
    },
  ],

  // ─── M11: 最终真相 ─────────────────────────────────────────────────────────
  truth: {
    killer: '王建国',
    method: '以仓库内金属管击打林雪峰枕部左侧致颅内出血死亡',
    motive: '林雪峰强制执行撤资协议，导致王建国债务崩盘，走投无路下的情绪失控',
    process: [
      '约林雪峰至废弃仓库进行最后谈判',
      '谈判破裂，林雪峰转身拒绝，王建国情绪失控',
      '捡起仓库内金属管击打林雪峰头部',
      '确认死亡后仓皇离开，未发现戒指脱落',
    ],
    keyClues: ['金属戒指（e2）', '手机基站数据（e4）', '撤资协议（e3）'],
    twist: '王建国并非预谋杀人——他本想谈判，金属管是临时起意。但这不影响他承担故意伤害致死的责任。',
    hiddenContext: '林雪峰的海外账户中，那笔准备转走的资金原来有一部分是王建国的合法投资——王建国才是真正的受害者之一。但法律不允许以牙还牙。',
    moralConclusion: '绝望是最危险的武器，而它通常指向的不是敌人，而是自己。',
  },

  // ─── M12: 评分标准 ─────────────────────────────────────────────────────────
  scoringCriteria: {
    totalMaxPoints: 100,
    timeBonus: '25分钟内完成额外+10分，35分钟内+5分',
    categories: [
      {
        name: '真凶识别',
        maxPoints: 40,
        description: '正确指出真凶姓名',
        criteria: ['准确指出王建国 +40分', '指出其他嫌疑人 +0分'],
      },
      {
        name: '手法还原',
        maxPoints: 25,
        description: '还原作案手法',
        criteria: ['完整说出"钝器/金属管/头部打击"核心要素 +25分', '只说"钝器伤人" +15分', '仅说"手法不明" +0分'],
      },
      {
        name: '动机分析',
        maxPoints: 20,
        description: '正确说明动机',
        criteria: ['提及"撤资/债务/走投无路" +20分', '只说"商业纠纷" +10分'],
      },
      {
        name: '证据运用',
        maxPoints: 15,
        description: '引用关键证据',
        criteria: ['引用戒指+基站数据+撤资协议 +15分', '引用任意两条 +10分', '引用一条 +5分'],
      },
    ],
    rankThresholds: [
      { minScore: 95, rank: '传奇侦探', badge: '🏆' },
      { minScore: 85, rank: '资深侦探', badge: '🥇' },
      { minScore: 70, rank: '优秀推理', badge: '🥈' },
      { minScore: 55, rank: '合格侦探', badge: '🥉' },
      { minScore: 0, rank: '见习侦探', badge: '📋' },
    ],
  },

  // ─── M13: 玩家错误推理 ─────────────────────────────────────────────────────
  wrongReasonings: [
    {
      suspectName: '陈美玲',
      falseClues: ['曾雇私家侦探调查死者', '动机极强（财产分割）', '助理离开后无法核实时间'],
      reasoningPath: '玩家可能认为：陈美玲作为律师有能力周密策划，掌握死者资产转移证据，动机比王建国更合理。',
      whyItSeemsPossible: '她的不在场证明有漏洞，且性格冷静完全符合"预谋杀人者"的心理画像。',
      correctingClue: '但现场DNA对应戒指内壁的"W.J.G"——这不属于陈美玲。她的调查手段是法律途径，而非暴力。',
    },
    {
      suspectName: '李晓雯',
      falseClues: ['情感受创，动机为情仇', '便利店距仓库仅18分钟路程', '她掌握死者违法邮件'],
      reasoningPath: '玩家可能认为：李晓雯被逼堕胎，情绪崩溃下实施了报复。',
      whyItSeemsPossible: '情绪激动的人往往被认为更可能冲动犯罪，而且她并无强有力的不在场证明。',
      correctingClue: '法医报告显示伤口为精准的枕部单击，力道强劲——这更符合有力量的成年男性，而非她的体型。另外，她的微表情显示的是真实悲痛，而非撒谎的心理特征。',
    },
  ],

  // ─── Legacy Red Herrings ────────────────────────────────────────────────────
  redHerrings: [
    '陈美玲曾雇私家侦探（实为法律手段，非凶手行为）',
    '李晓雯的怀孕秘密（是强烈动机，但不等于行凶）',
  ],

  // ─── M14: 彩蛋 ─────────────────────────────────────────────────────────────
  easterEggs: [
    {
      id: 'egg1',
      name: '消失的第四通电话',
      description: '林雪峰手机有一通记录被彻底抹除，但通话时长12分钟——那通电话的对方是陈美玲。他们在案发当天曾秘密通话。',
      triggerCondition: '审讯陈美玲时追问"你最后一次和死者通话是什么时候"',
      hiddenIn: '死者手机取证报告的第二页（默认不显示）',
      reward: '解锁隐藏对话：陈美玲承认她劝林雪峰不要去仓库，但他没听',
      loreHint: '陈美玲或许比看起来更希望林雪峰活着——因为他的死让海外账户证据随之消失了。',
    },
    {
      id: 'egg2',
      name: '王建国的日记',
      description: '在王建国书房抄家时发现一本加密日记，最后一页写着："如果明天谈判还是失败，我已经想好怎么做了。"日期是案发前一天。',
      triggerCondition: '在推理室中将"计划性"节点与"王建国"连接',
      hiddenIn: '推理室关系图中的隐藏节点',
      reward: '揭示真相：这不是完全的冲动犯罪——他提前想过，但直到那一刻才真正动手',
      loreHint: '计划和冲动之间的边界，比任何人想象的都要模糊。',
    },
  ],

  // ─── M15: 成就 ─────────────────────────────────────────────────────────────
  achievements: [
    {
      id: 'ach1',
      name: '如有神助',
      description: '在25分钟内完成全部推理并正确识别真凶',
      icon: '⚡',
      condition: '完成时间 ≤ 25分钟 且 真凶正确',
      reward: '称号「闪电侦探」+ 积分×1.5',
      rarity: 'epic',
    },
    {
      id: 'ach2',
      name: '铁证如山',
      description: '在推理中引用了全部4条关键证据',
      icon: '🔍',
      condition: '推理文本中提及e1/e2/e3/e4',
      reward: '额外+15推理积分',
      rarity: 'rare',
    },
    {
      id: 'ach3',
      name: '心理学家',
      description: '通过审讯发现王建国的微表情矛盾，并在推理中提及',
      icon: '🧠',
      condition: '审讯王建国至少3轮，且推理中提及"撒谎"或"矛盾"',
      reward: '解锁「审讯大师」称号',
      rarity: 'rare',
    },
    {
      id: 'ach4',
      name: '超级侦探',
      description: '触发所有隐藏彩蛋，发现案件的全部真相层',
      icon: '🏆',
      condition: '触发egg1和egg2',
      reward: '解锁「传说侦探」称号 + 专属档案封面',
      rarity: 'legendary',
    },
    {
      id: 'ach5',
      name: '人情练达',
      description: '在不引导的情况下主动询问李晓雯关于孩子的问题',
      icon: '💛',
      condition: '审讯李晓雯时主动提及"孩子"或"怀孕"',
      reward: '解锁李晓雯的完整档案和结局',
      rarity: 'common',
    },
  ],

  // ─── Legacy 字段（兼容旧 API/DB）────────────────────────────────────────────
  setting: '废弃工业仓库',
  deathMethod: '钝器击打头部致颅内出血',
  sceneDescription: '昏黄的路灯将仓库投影拉得极长。中央区域一具身着深色西装的男性仰面倒地，地面血迹向右延伸约1.5米，周围散落破碎木板和翻倒铁桶。',
};

export function createFallbackCase(difficulty: Difficulty): CaseData {
  return {
    ...TEMPLATE,
    id: generateId(),
    difficulty,
    createdAt: now(),
  };
}
